export default {
  yes: 'yes',
  no: 'no',
  all: 'All',
  startDate: 'Start Date',
  endDate: 'End Date',
  min: 'Min',
  max: 'Max',
  range: 'Range',
  equals: 'Equals',
  deleteConfirm: 'Are you sure you want to delete this record ?',
  select: 'Select',
  actions: 'Actions',
  relation: 'Relation',
  viewAll: 'View All',
  viewRelated: 'View Related',
  connected: 'Connected',
  connect: 'Connect',
  disConnect: 'DisConnect',
  editRow: 'Edit Row',
  viewRow: 'View Row',
  deleteRow: 'Delete Row',
  showing: 'Showing',
  of: 'of',
  results: 'results',
  goToFirstPage: 'Go to first page',
  goToLastPage: 'Go to last page',
  goPageNumber: 'Go Page Number',
  setPageSize: 'Set page size ',
  filter: 'Filter',
  save: 'Save',
  cancel: 'Cancel',
  close: 'close',
  create: 'create',
  update: 'update',
  view: 'view',
  isRequired: ' is required',
  show: 'SHOW',
};
