import { PrismaSelectOptions } from '@paljs/plugins';

export interface Settings<
  ModelName extends string = '',
  ModelsObject extends Record<ModelName, Record<string, any>> = Record<ModelName, Record<string, any>>,
> {
  /*
   * We will pass these options to `PrismaSelect` plugin.
   * */
  prismaSelectOptions?: PrismaSelectOptions<ModelName, ModelsObject>;
  /*
   * If you want to use Prisma Admin table generated by `@paljs/admin` package
   * You will need to add Queries and Mutation to get and update the table settings
   * @default false
   */
  includeAdmin?: boolean;
  /*
   * This is the path to the generated `adminSettings.json` file.
   * @default 'adminSettings.json'
   */
  adminSchemaPath?: string;
  /*
   * To exclude any default scalar, please add this option with an array
   * @example
   * {
   *  excludeScalar: ['Json', 'DateTime']
   * }
   */
  excludeScalar?: ('Json' | 'Decimal' | 'BigInt' | 'DateTime' | 'Bytes')[];
}
